"use client";
import styles from "../../styles/Home.module.css";
import Head from "next/head";
import Image from "next/image";
import { Button, Card, Col, Form, Input, List, Row, Typography } from "antd";
import { useRef, useState } from "react";

const Dashboard = () => {
  const ref = useRef(null);
  const getElementXpath = () => {
    console.log(ref.current.contentWindow.document.body);
  };
  const [targetUrl, setTargetUrl] = useState("https://kostzy.festiware.com/");
  const handleFinish = (values) => {
    const { targetUrl: formTargetUrl } = values;
    setTargetUrl(formTargetUrl);
  };

  const [data, setData] = useState(["Test Scenario 1", "Test Scenario 2"]);
  // const data = ["Test Scenario 1", "Test Scenario 2"];
  return (
    <div className={styles.container}>
      <Head>
        <title>Test Borg</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          display: "flex",
          flexDirection: "column",
          gap: "1rem",
          minHeight: "100vh",
        }}
      >
        <Row justify="center">
          <Col>
            <Form
              layout="inline"
              initialValues={{ targetUrl }}
              onFinish={handleFinish}
            >
              <Form.Item name="targetUrl" label="Target URL">
                <Input style={{ width: "40vw" }} />
              </Form.Item>
              <Form.Item>
                <Button htmlType="submit">Go</Button>
              </Form.Item>
            </Form>
          </Col>
        </Row>
        <Row
          style={{
            display: "flex",
            flexDirection: "column",
            gap: "1rem",
          }}
        >
          <Col>
            <iframe
              ref={ref}
              src={targetUrl}
              width="1920"
              height="1080"
              style={{ width: "100%" }}
            />
          </Col>
          <Col>
            <Card>
              <List
                header={
                  <div
                    style={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <Typography.Title level={4}>Test Scenario</Typography.Title>
                    <Button type="primary">Add</Button>
                  </div>
                }
                dataSource={data}
                renderItem={(item, i) => (
                  <List.Item>
                    <Typography.Text>{i + 1}.</Typography.Text> {item}
                  </List.Item>
                )}
              />
            </Card>
          </Col>
        </Row>
      </main>
    </div>
  );
};

export default Dashboard;
