"use client";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button, Form, Input } from "antd";
import { useState } from "react";
import { useRouter } from "next/router";

export const getServerSideProps = async () => {
  return {
    redirect: {
      destination: "/dashboard",
      permanent: true,
    },
  };
};

export default function Home() {
  return <></>;
  // const [targetUrl, setTargetUrl] = useState("https://kostzy.festiware.com/");
  // const handleFinish = (values) => {
  //   const { targetUrl: formTargetUrl } = values;
  //   setTargetUrl(formTargetUrl);
  // };
  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>Test Borg</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main
  //       style={{
  //         display: "flex",
  //         flexDirection: "column",
  //         gap: "1rem",
  //         padding: "4rem",
  //         minHeight: "100vh",
  //       }}
  //     >
  //       <div
  //         style={{
  //           display: "flex",
  //           flexDirection: "row",
  //           width: "100%",
  //         }}
  //       >
  //         <Form
  //           layout="inline"
  //           initialValues={{ targetUrl }}
  //           onFinish={handleFinish}
  //         >
  //           <Form.Item name="targetUrl">
  //             <Input style={{ width: "40vw" }} />
  //           </Form.Item>
  //           <Form.Item>
  //             <Button htmlType="submit">Go</Button>
  //           </Form.Item>
  //         </Form>
  //       </div>
  //       <iframe
  //         src={targetUrl}
  //         style={{ width: "100%", flex: 1 }}
  //         width="1920"
  //         height="1080"
  //       />
  //     </main>
  //   </div>
  // );
}
