"use client";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button, Form, Input } from "antd";
import { useState } from "react";

export default function Home() {
  const [targetUrl, setTargetUrl] = useState(
    "http://104.248.154.192:4000/katalog/"
  );
  const handleFinish = (values) => {
    const { targetUrl: formTargetUrl } = values;
    setTargetUrl(formTargetUrl);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          display: "flex",
          flexDirection: "column",
          gap: "1rem",
          padding: "4rem",
          minHeight: "100vh",
        }}
      >
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            width: "100%",
          }}
        >
          <Form
            layout="inline"
            initialValues={{ targetUrl }}
            onFinish={handleFinish}
          >
            <Form.Item name="targetUrl">
              <Input style={{ width: "40vw" }} />
            </Form.Item>
            <Form.Item>
              <Button htmlType="submit">Go</Button>
            </Form.Item>
          </Form>
        </div>
        <iframe src={targetUrl} style={{ width: "100%", flex: 1 }}></iframe>
      </main>
    </div>
  );
}
